### ISSUE TITLE
在windows上执行 npm start 报错：'NODE_ENV' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by wuzhuojun** [hubcarl/egg-typescript-element-kit#1]
在windows上执行 npm start 报错：'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
需要把 package.json 的 
"start": "NODE_ENV=production EGG_SERVER_ENV=prod node index.js",
修改为：
"start": "set NODE_ENV=production && set EGG_SERVER_ENV=prod && node index.js",

**Comment by hubcarl** [comment]
可以用 cross-env 解决，目前我已经加上 cross-env 配置了
